services:
  - type: web
    name: devops-flask-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
