global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'devops-flask-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask-app:5000']
        labels:
          app: 'devops-flask-app'
