apiVersion: v1
kind: Service
metadata:
  name: devops-flask-service
  labels:
    app: devops-flask-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
  selector:
    app: devops-flask-app
